name: Build test

on:
  push:
    branches-ignore:
      - "main"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          # gradle/gradle-daemon-jvm.propertiesのtoolchainVendor/Versionに合わせている
          distribution: zulu
          java-version: "21"

      # ComposePWAがnpx workboxを実行するため
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run tests
        run: ./gradlew :shared:jvmTest :shared:jsTest :shared:wasmJsTest

      - name: Build web app
        run: ./gradlew :webApp:wasmJsBrowserDistribution :webApp:jsBrowserDistribution
